### ISSUE TITLE
Background image on authentication page fails to load in production

### ISSUE THREAD

**Issue by moking55** [textures1245/csmju-comcamp-22nd-promote#8] opened 2023-12-01 21:06 UTC
When accessing the authentication page in the production environment, the background image fails to load, resulting in a broken user experience. The browser console displays an error message:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

This error indicates that the server is unable to locate the background image file, causing it to not display on the authentication page.

### Steps to Reproduce:

1. Open a web browser and navigate to the production environment of the application.
2. Access the authentication page.
3. Observe that the background image is missing, leaving a blank background behind.

### Expected Behavior:

The background image should load successfully and display seamlessly on the authentication page, enhancing the visual appeal and user experience.

### Actual Behavior:

The background image fails to load, resulting in a broken user experience. The missing background image detracts from the overall visual design and may lead to confusion among users.
![image](https://github.com/textures1245/csmju-comcamp-22nd-promote/assets/19747447/2ae0dc0a-9e15-4f40-8eb0-7e69d51c7cb1)

### Impact:

This bug negatively impacts the user experience by disrupting the visual appeal of the authentication page. The missing background image can make the page feel unfinished and may cause users to question the professionalism of the application.

### Priority:

Medium

### Resolution:

1. Verify the correct path to the background image file in the production environment. Ensure the file exists and is accessible.
2. Check the file permissions on the server to ensure the image file can be read by the web server.
3. Validate the file extension and mime type to ensure the server is correctly handling the image file.
4. Clear any caching or browser history that may be interfering with the loading of the background image.
5. If the issue persists, consider deploying the latest version of the application code to the production environment.

### Additional Notes:

1. This bug may be specific to certain browsers or devices. It is recommended to test the background image loading across different platforms.
2. If the background image is stored in a CDN (Content Delivery Network), ensure the CDN configuration is correct and the image file is properly cached.

**Comment by textures1245** [comment] 2023-12-02 06:37
I sincerely appreciate you taking the time to report this critical bug and providing detailed steps to reproduce it. The missing background image on the authentication page in the production environment undoubtedly affects the user experience and needs to be addressed promptly.

I have carefully **investigated the issue and identified the root cause** as the **invalid URLs** used for the background image. The r**elative paths were not targeting the correct asset source**, **leading to a 404 error** and the image failing to load.

To resolve this issue, I have replaced the invalid relative paths with the correct absolute URLs pointing to the appropriate asset source. This will ensure that the background image is successfully loaded and displayed on the authentication page, enhancing the visual appeal and providing a seamless user experience.

I tested these changes thoroughly to ensure that they resolved the issue and did not introduce any new bugs. And already committed this to the `a0c918b` commit version.

Thank you again for your valuable contribution to our project. Your attention to detail and prompt action have helped us maintain a positive user experience and prevent potential confusion among users.

**Closed by textures1245** 2023-12-02 06:37 UTC
Labels: bug
